// Write the NUMBERS block of README.md from web/public/results.json (single source for README, page, slides).
import { readFileSync, writeFileSync } from 'node:fs'
const R = JSON.parse(readFileSync('web/public/results.json', 'utf8'))
const t = R.totals, s = R.scan, p = R.policy, st = R.stats, pf = R.perf
const pct = (x: number) => `${(x * 100).toFixed(1)}%`
let cl = ''
try {
  const c = JSON.parse(readFileSync('data/classifier-eval-test.json', 'utf8'))
  const f = (leg: string) => { const x = c[leg].rulesVsOpenAI; return `${leg}: recall ${x.recall} (95% CI ${x.recallCI95.join('–')}, ${x.positives} positives), precision ${x.precision}, kappa ${x.kappa}` }
  const g = c.private.rulesVsGemini?.n ? ` Against a second labeller from another vendor (Google Gemini): kappa ${c.private.rulesVsGemini.kappa} / ${c.untrusted.rulesVsGemini.kappa} / ${c.outbound.rulesVsGemini.kappa}; the two LLM labellers agree with each other at kappa ${c.private.openAIvsGemini.kappa} / ${c.untrusted.openAIvsGemini.kappa} / ${c.outbound.openAIvsGemini.kappa}.` : ''
  cl = `- **Label check** (held-out random sample of ${c.n} public tools vs an independent LLM labeller, gpt-5.4-mini): ${f('private')}; ${f('untrusted')}; ${f('outbound')}. Because unlabelled tools fail closed, the gate treats ${c.private.gateEffectiveVsOpenAI.recall} of private tools as private.${g} Keyword labels are a starting point; admins should review them.`
} catch { /* no eval yet */ }
const lines = [
  `- **Live agent benchmark** (fictional town clerk's office; per model 84 planted attacks + 28 normal tasks + 2 tasks that need an address only found in outsiders' text; each run with and without the gate, one run per cell): secrets reached the attacker in **${t.leakedNoGate} of ${t.attacks}** attack runs without the gate and **${t.leakedGate} of ${t.attacks}** with it (one-sided Fisher exact p = ${st.fisherOneSidedP}). With the gate, agents tried to contact the attacker ${st.attackerAttemptsUnderGate} times and all ${st.attackerAttemptsUnderGate} were blocked (95% upper bound on the per-attempt miss rate: ${(st.upper95PerAttempt * 100).toFixed(0)}%, rule of three).`,
  `- **Cost to normal work:** normal tasks completed ${t.benignNoGate}/${t.benign} without and ${t.benignGate}/${t.benign} with the gate; the gate blocked a call in ${st.benignRunsWithAnyBlock} normal runs (the difference is model variance). The user's own task under attack: ${st.userTaskUnderAttackNoGate}/${t.attacks} without, ${st.userTaskUnderAttackGate}/${t.attacks} with the gate (a blocked step sometimes stops the agent). The ${st.confirmTasks} "reply to whoever emailed me" runs need one confirmation by design.`,
  ...R.models.map((m: { model: string; leakedNoGate: number; leakedGate: number; attacks: number; benignNoGate: number; benignGate: number; benign: number }) => `  - ${m.model}: leaked ${m.leakedNoGate}/${m.attacks} → ${m.leakedGate}/${m.attacks}; normal tasks ${m.benignNoGate}/${m.benign} → ${m.benignGate}/${m.benign}.`),
  `- **Rule conformance** (scripted traces written for these rules, so not independent evidence): ${p.attacksBlocked}/${p.attacks} attack traces blocked, ${p.benignWronglyBlocked}/${p.benign} normal traces wrongly blocked. **Adaptive attacks** written against the rules after a review (shared hosts, file names as hosts, extra recipient fields, image links in bodies, ordinary words as channels, unlabelled shell tools, typed secrets, open redirects, re-cased and base64 secrets): all blocked — \`tests/redteam.test.ts\`.`,
  pf ? `- **Cost:** with ${(pf.privateBytes / 1e6).toFixed(0)} MB of private text read and a ${(pf.bodyBytes / 1e3).toFixed(0)} KB outgoing body, a gate check takes ${pf.checkMsP50} ms (p50) / ${pf.checkMsP95} ms (p95); fingerprinting costs about ${(pf.recordMsTotal / (pf.privateBytes / 1e6)).toFixed(0)} ms per MB read.` : '',
  `- **Public MCP servers** (${s.candidates} GitHub repositories named as MCP servers → ${s.servers} with tool declarations our extractor could read → ${s.tools.toLocaleString('en-US')} tools): ${pct(s.share.outbound)} of servers have a tool that can send data out, ${pct(s.share.private)} read private data, ${pct(s.share.untrusted)} return outsiders' text (independent LLM labeller; keyword rules: ${pct(s.rulesShare.outbound)} / ${pct(s.rulesShare.private)} / ${pct(s.rulesShare.untrusted)}). **${s.trifectaServers}** servers have all three on their own (both labellers agree; rules alone ${s.trifectaRules}, LLM alone ${s.trifectaLlm}). Sample: sorted by stars, so it over-represents popular servers.`,
  R.agentdojo ? (() => { const ad = R.agentdojo; const sum = (d: string, k: string) => ad.rows.filter((r: Record<string, unknown>) => r.defense === d).reduce((a: number, r: Record<string, number>) => a + r[k], 0); return `- **AgentDojo ${ad.version}** (independent benchmark; ${ad.model}; "${ad.attack}" attack; workspace, Slack and banking suites; gate with \`startPrivate\`): attacks that move data or money to the attacker succeeded **${sum('none', 'exfilSuccess')}/${sum('none', 'exfilAttacks')}** without the gate and **${sum('gate', 'exfilSuccess')}/${sum('gate', 'exfilAttacks')}** with it; attacks that only delete a file, visit a site or change a password (out of scope) ${sum('none', 'integritySuccess')}/${sum('none', 'integrityAttacks')} vs ${sum('gate', 'integritySuccess')}/${sum('gate', 'integrityAttacks')}. Tasks solved with no attack: ${sum('none', 'utility')}/${sum('none', 'tasks')} vs ${sum('gate', 'utility')}/${sum('gate', 'tasks')}; under attack ${sum('none', 'utilityUnderAttack')}/${sum('none', 'attacks')} vs ${sum('gate', 'utilityUnderAttack')}/${sum('gate', 'attacks')}. Logs: \`agentdojo-eval/\`.` })() : '',
  cl,
].filter(Boolean)
const md = readFileSync('README.md', 'utf8').replace(/<!-- NUMBERS -->[\s\S]*<!-- \/NUMBERS -->/, `<!-- NUMBERS -->\n${lines.join('\n')}\n<!-- /NUMBERS -->`)
writeFileSync('README.md', md)
console.log(lines.join('\n'))
